# Site settings
title:          Quasar
description:    "Đặng Minh Đông"
baseurl:        "https://dongpro123.gthub.io"
url:            "https://dongpro123.github.io"

# Author
author:
  name:         Đông
  email:        123@321.vn

# Build settings
markdown:       kramdown

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji 

# Permalinks
permalink:      /:title/
paginate:       12
